version: "3"
containers:
- name: cloud-client
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
  ports:
  - 80
gcp_projects:
- name: gcpproject
  services:
  - compute.googleapis.com
  - container.googleapis.com
  - cloudresourcemanager.googleapis.com
  - dns.googleapis.com
  - iamcredentials.googleapis.com
  - iam.googleapis.com
  - serviceusage.googleapis.com
  - storage-api.googleapis.com
  - storage-component.googleapis.com
  - storage.googleapis.com
  - cloudapis.googleapis.com
  - servicemanagement.googleapis.com
  - cloudapis.googleapis.com
  roles:
  - roles/container.admin
  - roles/iam.serviceAccountUser
  - roles/compute.admin
  - roles/storage.admin
  - roles/dns.admin
  - roles/servicemanagement.quotaViewer
  - roles/iam.roleAdmin
  - roles/iam.securityAdmin
  - roles/iam.serviceAccountAdmin
  - roles/iam.serviceAccountKeyAdmin
secrets:
- name: CCROW_ROUTE53_ACCESSKEY
- name: CCROW_ROUTE53_SECRETKEY
- name: CCROW_REDHAT_PULLSECRET
- name: CCROW_REDHAT_REGISTRYSECRET
- name: PXENT_LICENSE
