kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster
  namespace: portworx
  annotations:
    portworx.io/install-source: https://install.portworx.com/?operator=true&mc=false&kbver=1.28.14&ns=portworx&b=true&s=%2Fdev%2Fsdb&j=auto&c=px-cluster&gke=true&stork=true&csi=true&mon=true&tel=false&st=k8s&promop=true
    portworx.io/is-openshift: 'true'
spec:
  image: portworx/oci-monitor:3.1.6
  imagePullPolicy: Always
  kvdb:
    internal: true
  storage:
    devices:
      - /dev/sdc
    journalDevice: auto
  secretsProvider: k8s
  stork:
    enabled: true
    args:
      webhook-controller: 'true'
  autopilot:
    enabled: true
  csi:
    enabled: true
  monitoring:
    telemetry:
      enabled: false
    prometheus:
      enabled: true
      exportMetrics: true
